# Generated by Django 3.0.7 on 2020-06-07 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('-date_created',)},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='data_created',
            new_name='date_created',
        ),
    ]
