# Generated by Django 3.0.7 on 2020-06-21 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_detailserview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetailSerview',
            new_name='DetailService',
        ),
    ]
