# Generated by Django 3.0.7 on 2020-06-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_appointment_pricingplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='features',
            field=models.ManyToManyField(related_name='pricing_plans', to='core.PricingFeature'),
        ),
    ]
