# Generated by Django 3.0.7 on 2020-06-23 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200623_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricingplan',
            old_name='description',
            new_name='main_feature',
        ),
    ]
