# Generated by Django 3.0.7 on 2020-06-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200623_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingplan',
            name='main_feature',
            field=models.CharField(max_length=100),
        ),
    ]
