# Generated by Django 3.0.7 on 2020-06-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200623_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingplan',
            name='main_feature',
            field=models.CharField(max_length=50),
        ),
    ]
