# Generated by Django 3.0.7 on 2020-06-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200623_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingplan',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
