# Generated by Django 3.0.7 on 2020-06-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200623_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='venue',
            field=models.CharField(default='kintampo', max_length=500),
            preserve_default=False,
        ),
    ]
