# Generated by Django 3.0.7 on 2020-06-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_appointment_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.CharField(default='054688270', max_length=10),
            preserve_default=False,
        ),
    ]
