# Generated by Django 3.0.7 on 2020-06-25 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
