# Generated by Django 3.0.7 on 2020-06-25 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200625_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='appointment/files')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Appointment')),
            ],
        ),
    ]
