# Generated by Django 3.0.7 on 2020-06-25 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_appointmentfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentfile',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_files', to='core.Appointment'),
        ),
    ]
