# Generated by Django 3.0.7 on 2020-06-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200625_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentfile',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
